In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('result.csv')

In [3]:
df.head(10)

,animal_id,datetime_intake,found_location,intake_type,intake_condition,animal_type_intake,name_intake,sex_intake,color_intake,breed_type,datetime_outcome,outcome_type,sex_upon_outcome,fixed_changed,age_bucket,datetime_length
0,A730601,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,No,Intact Male,Tabby,Mix,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,74940000000000
1,A676515,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Yes,Intact Male,Bicolor,Mix,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,294780000000000
2,A679549,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Yes,Intact Male,Bicolor,Mix,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,2153460000000000
3,A683798,2016-07-21 12:16:00,3118 Windsor Rd in Austin (TX),Stray,Normal,Cat,Yes,Spayed Female,Bicolor,Mix,2016-10-18 10:55:00,Adoption,Spayed Female,0,1-3 years,7684740000000000
4,A683656,2014-07-13 13:20:00,8238 Research Blvd in Austin (TX),Stray,Normal,Cat,No,Intact Male,Point,Mix,2014-07-17 16:57:00,Adoption,Neutered Male,1,1-6 months,358620000000000
5,A709749,2015-08-12 18:29:00,4800 Weletka Dr in Austin (TX),Stray,Normal,Cat,Yes,Intact Female,Tabby,Mix,2015-09-22 12:49:00,Transfer,Spayed Female,1,1-3 years,3522000000000000
6,A733551,2016-08-23 14:35:00,183 And Cameron in Austin (TX),Stray,Normal,Cat,Yes,Intact Male,Bicolor,Mix,2016-09-01 00:00:00,Transfer,Intact Male,0,1-6 months,725100000000000
7,A732960,2016-08-15 15:08:00,6808 S Ih 35 Frontage Rd in Austin (TX),Stray,Normal,Cat,Yes,Intact Female,Tabby,Mix,2016-08-19 18:27:00,Adoption,Spayed Female,1,1-6 months,357540000000000
8,A720597,2016-02-12 14:35:00,8413 Danville Dr in Austin (TX),Stray,Medical,Dog,Yes,Intact Male,Blue,Mix,2016-02-19 16:20:00,Transfer,Intact Male,0,1-3 years,611100000000000
9,A671219,2014-01-21 11:19:00,11602 Gunsmoke Circle in Austin (TX),Stray,Normal,Cat,No,Intact Male,Point,Mix,2014-01-21 15:13:00,Transfer,Intact Male,0,1-3 years,14040000000000

In [4]:
from geopy.geocoders import Nominatim

In [10]:
locator = Nominatim(user_agent='myGeocoder')

In [11]:
address=['1109 Shady Ln in Austin (TX)',
 '615 E. Wonsley in Austin (TX)',
 '124 W Anderson in Austin (TX)',
 '3118 Windsor Rd in Austin (TX)',
 '8238 Research Blvd in Austin (TX)',
 '4800 Weletka Dr in Austin (TX)',
 '183 And Cameron in Austin (TX)',
 '6808 S Ih 35 Frontage Rd in Austin (TX)',
 '8413 Danville Dr in Austin (TX)']

In [12]:
lst=[]
for i in address:
    location = locator.geocode(i)
    lst.append(location)
    print('Generating location: '+i)
    
print('-----------------------------------')
print("--------------Done-----------------")
lst

Generating location: 1109 Shady Ln in Austin (TX)
Generating location: 615 E. Wonsley in Austin (TX)
Generating location: 124 W Anderson in Austin (TX)
Generating location: 3118 Windsor Rd in Austin (TX)
Generating location: 8238 Research Blvd in Austin (TX)
Generating location: 4800 Weletka Dr in Austin (TX)
Generating location: 183 And Cameron in Austin (TX)
Generating location: 6808 S Ih 35 Frontage Rd in Austin (TX)
Generating location: 8413 Danville Dr in Austin (TX)
-----------------------------------
--------------Done-----------------

[None,
 Location(615, East Wonsley Drive, Georgian Acres, Austin, Travis County, Texas, 78753, United States, (30.343954467336683, -97.69976176884421, 0.0)),
 None,
 None,
 None,
 None,
 Location(Cameron Road, Coronado Hills, Austin, Travis County, Texas, 78753:78754, United States, (30.329702, -97.689667, 0.0)),
 None,
 None]

In [13]:

from geopy.extra.rate_limiter import RateLimiter

In [16]:
df_test=pd.DataFrame(data=df['found_location']).iloc[0:5,:]
df_test

                      found_location
0       1109 Shady Ln in Austin (TX)
1      615 E. Wonsley in Austin (TX)
2      124 W Anderson in Austin (TX)
3     3118 Windsor Rd in Austin (TX)
4  8238 Research Blvd in Austin (TX)

In [18]:
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)
# 2- - create location column
df_test['location'] = df_test['found_location'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_test['point'] = df_test['location'].apply(lambda loc: tuple(loc.point) if loc else None)
# 4 - split point column into latitude, longitude and altitude columns
# df_test[['latitude', 'longitude', 'altitude']] = pd.DataFrame(df_test['point'].tolist(), index=df_test.index)

In [20]:
df_test.head()

,found_location,location,point
0,1109 Shady Ln in Austin (TX),None,None
1,615 E. Wonsley in Austin (TX),"(615, East Wonsley Drive, Georgian Acres, Aust...","(30.343954467336683, -97.69976176884421, 0.0)"
2,124 W Anderson in Austin (TX),None,None
3,3118 Windsor Rd in Austin (TX),None,None
4,8238 Research Blvd in Austin (TX),None,None